apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-ha-rolebinding
  namespace: jenkins
  labels:
    app: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins-ha-sa
    namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-ha-role
